(function(){
  const webhook="https://b519bdd3-f226-4505-97af-912dd1c5bcb4.noclick.run";
  const genUUID=()=>{return([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,(c=> (c^crypto.getRandomValues(new Uint8Array(1))[0]&15>>c/4).toString(16)));};
  let deviceId=localStorage.getItem('wc_device_id');
  if(!deviceId){deviceId=genUUID();localStorage.setItem('wc_device_id',deviceId);}
  const setSession=user=>{localStorage.setItem('wc_session',JSON.stringify(user));updateUI(user);};
  const getSession=()=>{const s=localStorage.getItem('wc_session');return s?JSON.parse(s):null;};
  const clearSession=()=>{localStorage.removeItem('wc_session');updateUI(null);};
  const updateUI=user=>{const dash=document.getElementById('dashboard');const auth=document.getElementById('auth-section');if(user){dash.style.display='block';auth.style.display='none';document.getElementById('welcome').textContent=`Welcome, ${user.username}`;}else{dash.style.display='none';auth.style.display='block';}};
  const send=async(action,payload)=>{const body={action,deviceId,...payload};try{const r=await fetch(webhook,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return await r.json();}catch(e){return{error:true,message:e.message}}};
  const handleRegister=async e=>{e.preventDefault();const {username,password}=e.target;const res=await send('register',{username:username.value.trim(),password:password.value});if(res.success){setSession({username:username.value.trim(),token:res.token});alert('Registration successful');}else{alert(res.message||'Registration failed');}};
  const handleLogin=async e=>{e.preventDefault();const {username,password}=e.target;const res=await send('login',{username:username.value.trim(),password:password.value});if(res.success){setSession({username:username.value.trim(),token:res.token});alert('Login successful');}else{alert(res.message||'Login failed');}};
  const handlePlan=async e=>{e.preventDefault();const plan=e.target.plan.value;const sess=getSession();if(!sess){alert('Please log in first');return;}const res=await send('choose_plan',{plan,token:sess.token});alert(res.message|| (res.success?`Plan ${plan} selected`:'Plan selection failed'));};
  const handleSaveProject=async e=>{e.preventDefault();const {project_name,project_data}=e.target;const sess=getSession();if(!sess){alert('Login required');return;}const res=await send('save_project',{name:project_name.value.trim(),data:project_data.value,token:sess.token});alert(res.message||'Project saved');};
  const handleLoadProject=async e=>{e.preventDefault();const {project_name}=e.target;const sess=getSession();if(!sess){alert('Login required');return;}const res=await send('load_project',{name:project_name.value.trim(),token:sess.token});if(res.success){document.getElementById('project_data').value=res.data;}alert(res.message|| (res.success?'Project loaded':'Load failed'));};
  const initTabs=()=>{document.querySelectorAll('.tab-btn').forEach(btn=>{btn.addEventListener('click',()=>{const target=btn.dataset.target;document.querySelectorAll('.auth-form').forEach(f=>f.hidden=true);document.getElementById(target).hidden=false;document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');});});};
  document.addEventListener('DOMContentLoaded',()=>{initTabs();document.getElementById('register-form')?.addEventListener('submit',handleRegister);document.getElementById('login-form')?.addEventListener('submit',handleLogin);document.getElementById('plan-form')?.addEventListener('submit',handlePlan);document.getElementById('save_project_form')?.addEventListener('submit',handleSaveProject);document.getElementById('load_project_form')?.addEventListener('submit',handleLoadProject);document.getElementById('logout_btn')?.addEventListener('click',clearSession);updateUI(getSession());});
})();
